name: demo workflow
on: push
jobs:
    demo-job:
        runs-on: macos-26
        steps:
            - name: Run a test script
              run: echo "Hello World"
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                node-version: 22
            - name: Install dependencies
              run: npm install
            - name: Run Express App
              run: node server.js
            - name: Terminate Express App
              run: kill $(lsof -t -i:3000)
            - name: Run Jest tests
              run: npm run test
