name: demo workflow
on: 
  push:
    branches:
      - main
jobs:
    demo-job:
        runs-on: macos-26
        steps:
            - name: Run a test script
              run: echo "Hello World"
            - name: Check Variables
              run: echo "server is ${{ runner.os }}, repository is ${{ github.repository }}, branch is ${{ github.ref }}, variable SERVER_NAME is ${{ env.SERVER_NAME }}, secret MY_SECRET is ${{ secrets.PASSWORD }}"
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                node-version: 22
            - name: Install dependencies
              run: npm install
            - name: Run Express App and Terminate it after 5 seconds
              run: node server.js & sleep 5
            - name: Run Jest tests
              run: npm run test
