name: demo workflow
on: push
jobs:
    demo-job:
        runs-on: ubuntu-latest
        # environment: development
        env:
            SERVER_NAME: ${{ vars.SERVER_NAME}}
            PASSWORD: ${{ secrets.PASSWORD }}
        steps:
            # - name: Run a test script
            #   run: echo "Hello World"
            # - name: OS and Repo Info
            #   run: |
            #     echo "This job is running on a ${{ runner.os }} server"
            #     echo "The repository is ${{ github.repository }}"
            #     echo "The branch or tag ref that triggered the workflow is ${{ github.ref }}"
            # - name: Check Variables
            #   run:  echo "variable SERVER_NAME is $SERVER_NAME, secret MY_SECRET is $PASSWORD"
            # - uses: actions/checkout@v4
            # - name: Use Node.js
            #   uses: actions/setup-node@v3
            #   with:
            #     node-version: 22
            # - name: Install dependencies
            #   run: npm install
            # - name: Run Express App and Terminate it after 5 seconds
            #   run: node server.js & sleep 5
            # - name: Run Jest tests
            #   run: npm run test
            - name: 🚚 Get latest code
              uses: actions/checkout@v4
            - name: Upload Files to Server via SFTP
              uses: SamKirkland/FTP-Deploy-Action@v4.3.6
              with:
                server: ${{ vars.SERVER_NAME }}
                port: 22
                timeout: 600000
                username: root
                password: ${{ secrets.PASSWORD }}
                # local-dir: ${{ github.repository }}
                server-dir: /root/deployer/cicd-app/
                exclude: |
                  **/.git*
                  **/.git*/**
                  **/node_modules/**
                  **/n8n*/**
            - name: SSH into Server and Run Application
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ vars.SERVER_NAME }}
                username: root
                password: ${{ secrets.PASSWORD }}
                script: |
                  cd /root/deployer/cicd-app
                  docker-compose -f compose.yaml up -d --build
